# Don't print a new line at the start of the prompt
add_newline = false

# makes prompt a single line
[line_break]
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[λ](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
vicmd_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"
